/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package minidecaf;

import java.io.FileWriter;

public class Main {
    public static void main(String[] args) throws Exception {
        try (var writer = new FileWriter(args[1])) {
            writer.write(new Compiler().run());
        }
    }
}
